openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SMARTBEARD192M/FF-ICE_Demo/1.0.1
info:
  description: API for FF-ICE Demo App
  version: "1.0.1"
  title: FF-ICE Demo API
  contact:
    email: a.arango@tu-braunschweig.de
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /flightplans:
    post:
      summary: Submit a new flight plan
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FlightPlan"
      responses:
        "201":
          description: Flight plan created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FlightPlan"
        "400":
          description: Invalid flight plan data
    get:
      summary: Retrieve all flight plans
      responses:
        "200":
          description: Array of flight plans
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FlightPlan"

  /flightplans/{flightId}:
    get:
      summary: Retrieve a specific flight plan
      parameters:
        - in: path
          name: flightId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Flight plan details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FlightPlan"
        "404":
          description: Flight plan not found
  /routes:
    get:
      description: "All flight routes"
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FlightRoute"
      summary: Get all routes
      tags:
        - default
    post:
      description: Save a new route
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FlightRoute"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  insertedId:
                    type: string
                    description: Id of the inserted record
components:
  schemas:
    Location:
      type: object
      required:
        - latitude
        - longitude
      properties:
        latitude:
          type: number
          minimum: -90
          maximum: 90
          description: "Latitude"
        longitude:
          type: number
          minimum: -180
          maximum: 180
          description: "Longitude"
        altitude:
          type: number
          minimum: -5000
          maximum: 200000
          description: "Altitude in ft"
    Waypoint:
      type: object
      required:
        - waypointId
      properties:
        waypointId:
          type: string
          description: "Unique waypoint id"
          maxLength: 5
          minLength: 3
        location:
          $ref: "#/components/schemas/Location"
    FlightRoute:
      type: object
      required:
        - routeId
      properties:
        routeId:
          type: string
          description: Route id
        waypoints:
          type: array
          items:
            $ref: "#/components/schemas/Waypoint"
    FlightPlan:
      type: object
      required:
        - flightId
        - aircraftId
        - flightRules
        - departure
        - route
        - destination
        - altitude
        - estimatedElapsedTime
        - status
      properties:
        flightId:
          type: string
          description: Unique identifier of the flight plan
        aircraftId:
          type: string
          description: Unique identifier of the aircraft
        flightRules:
          type: string
          enum: [IFR, VFR]
          description: Indicates Instrument or Visual Flight Rules
        departure:
          type: object
          properties:
            airport:
              type: string
              format: icao
              description: ICAO code of the departure airport
            time:
              type: string
              format: date-time
              description: Departure time in ISO8601 format (UTC)
        destination:
          # Similar structure as 'departure'
          type: object
          properties:
            airport:
              type: string
              format: icao
        route:
          $ref: "#/components/schemas/FlightRoute"
        altitude:
          type: string
          description: Flight Level (e.g., FL350)
        estimatedElapsedTime:
          type: string
          format: duration
          description: Estimated flight time (ISO 8601 Duration format)
        status:
          type: string
          enum: [pending, approved, rejected]
          default: pending
