import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Provider from "@/components/Provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { twJoin } from "tailwind-merge";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FF-ICE Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twJoin(
          inter.className,
          "h-screen flex flex-col bg-slate-900 text-slate-200"
        )}
      >
        <Provider>
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
